# To separate npm/node runtimes from the host computer
services:
  ghbnav:
    image: node:20-bookworm-slim
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true
    command: bash
    ports:
      - 5173:5173
